apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
data:
  jwt: NEJ6bUd0MjZSVGNR4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCi4oCiWHJwZWdzcVZEb3U0

